pre-commit:
  jobs:
    - name: Js Format
      glob:
        - "*.css"
        - "*.js"
        - "*.ts"
      run: npm run format

    - name: Js Lint
      glob:
        - "*.css"
        - "*.js"
        - "*.ts"
      run: npm run lint

    - name: Actions Lint
      glob: ".github/workflows/*.yml"
      run: actionlint
